import {reactive} from "vue";

export default reactive([
    { type:0, level:1, col:0,row:0, heroIndex:0, valid:true, costs:1, name:'Cavalry',},
    { type:0, level:1, col:0,row:1, heroIndex:0, valid:true, costs:1, name:'Sparta',   },
    { type:0, level:1, col:0,row:2, heroIndex:1, valid:false, costs:1, name:'Mercenary', requirement:'Level 5 Achilles' },
    { type:0, level:1, col:0,row:3, heroIndex:1, valid:true, costs:1, name:'Knight', requirement:'Level 10 Achilles' },
    { type:0, level:1, col:1,row:0, heroIndex:0, valid:false, costs:1, name:'Archer', requirement:'Level 5 Odysseus',      },
    { type:0, level:1, col:1,row:1, heroIndex:0, valid:true, costs:1, name:'Viking warrior', },
    { type:0, level:1, col:1,row:2, heroIndex:1, valid:true, costs:1, name:'Priest',  requirement:'Level 5 Achilles',       },
    { type:0, level:1, col:1,row:3, heroIndex:2, valid:false, costs:1, name:'Red Dragon',   requirement:'Level 5 Apollo',  },
    { type:1, level:1, col:2,row:0, valid:true, costs:1, name:'Volley',     },
    { type:1, level:1, col:2,row:1, valid:true, costs:1, name:'Fire rocks', },
    { type:2, level:1, col:2,row:2, valid:true, costs:2, name:'Top speed',   },
    { type:2, level:1, col:2,row:3, valid:true, costs:2, name:'Revive',     },
    { type:1, level:1, col:3,row:0, valid:true,costs:1, name:'Blood strike',   },
    { type:1, level:1, col:3,row:1, valid:false,costs:1, name:'Excalibur',      },
    { type:2, level:1, col:3,row:2, valid:false,costs:1, name:'Fire strike',    },
    { type:0, level:1, col:3,row:3, valid:false,costs:5, name:'Fire avalanche', },
    { type:0, level:1, col:4,row:0, costs:3, name:'Purgatory',      },
    { type:1, level:1, col:4,row:1, costs:2, name:'Rain of Fire',   },
    { type:1, level:1, col:4,row:2, costs:2, name:'Fire explosive', },
    { type:1, level:1, col:4,row:3, costs:5, name:'Burn',           },
    { type:1, level:1, col:5,row:0, costs:5, name:'Thunderbolt',    },
    { type:1, level:1, col:5,row:1, costs:5, name:'Wrath of zeus',  },
    { type:2, level:1, col:5,row:2, costs:2, name:'Avatar',         },
    { type:1, level:1, col:5,row:3, costs:5, name:'Soul attack',    },
    { type:0, level:1, col:6,row:0, costs:5, name:'Siren charm',    },
    { type:1, level:1, col:6,row:1, costs:5, name:'Storm',          },
    { type:1, level:1, col:6,row:2, costs:5, name:'Tsunami',        },
    { type:1, level:1, col:6,row:3, costs:5, name:'Frost strike',   },
    { type:1, level:1, col:7,row:0, costs:6, name:'灵魂鞭笞' },
    { type:1, level:1, col:7,row:1, costs:6, name:'灵魂爆炸' },
    { type:1, level:1, col:7,row:2, costs:3, name:'死亡凋零' },
    { type:2, level:1, col:7,row:3, costs:3, name:'亡者之心' },
    { type:0, level:1, col:8,row:0, costs:2, name:'神兵天降' },
    { type:2, level:1, col:8,row:1, costs:5, name:'治疗之光' },
    { type:1, level:1, col:8,row:2, costs:3, name:'自然之力' },
    { type:1, level:1, col:8,row:3, costs:3, name:'惩戒之光' },
    { type:2, level:1, col:9,row:0, costs:2, name:'生灵涂炭' },
    { type:0, level:1, col:9,row:1, costs:2, name:'荆棘蔓延' },
    { type:0, level:1, col:9,row:2, costs:3, name:'复仇之魂' },
    { type:0, level:1, col:9,row:3, costs:3, name:'恶魔大军' },
    { type:1, level:1, col:10,row:0, costs:3, name:'降魔' },
    { type:1, level:1, col:10,row:1, costs:3, name:'超度' },
    { type:2, level:1, col:10,row:2, costs:3, name:'异域' },
    { type:1, level:1, col:10,row:3, costs:5, name:'无妄天灾' },
])